stages:
  - build
  - install
build_base:
  stage: build
  trigger:
    project: rokkor/pibasekt
    branch: master
    strategy: depend
install:
  stage: install
  tags:
    - install
  script:
    - echo "build"
    - mvn install -DskipTests=true
