#update server 2 retry 6
stages:
#  - build
  - install
  - runtest
  - product_install
#  - tojk

#build_base:
#  stage: build
#  only:
#    refs:
#      - master
#  trigger:
#    project: rokkor/pibasekt
#    branch: master
#    strategy: depend


install:
  stage: install
  tags:
    - install
  image: docker:lastest
  services:
    - docker:dind
  before_script:
    - docker login --username kykub --password-stdin < /home/ky/d.txt
    # - docker login -u "$CI_REGISTRY_USER"  -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY 
    # - product_install
  script:
    - mvn install -Dspring.profiles.active=test
    # - ./mvnw package 
    - docker build -t kykub/pidevice --rm .
    - docker push kykub/pidevice
    - docker image prune -a -f
runtest:
  stage: runtest
  except:
    refs:
      - master
  tags:
    - runtest
  script:
    - CONTAINER_NAME="pidevice"
    - OLD="$(docker ps --all --quiet --filter=name="$CONTAINER_NAME")"
    - |- 
           if [ -n "$OLD" ]; then
            docker stop $OLD && docker rm $OLD
           fi
    - docker pull kykub/pidevice
    - docker run -p 3334:888 -d --name pidevice  --restart always -e TZ="Asia/Bangkok" -e JAVA_OPTS=" -Dspring.datasource.url=jdbc:h2:~/pp2;AUTO_SERVER=TRUE;IGNORECASE=TRUE  -Dfixip=192.168.88.20  -Dmac=b8:27:eb:19:8f:5f  -Dfile.encoding=UTF-8  -Dspring.profiles.active=pc  -Dpiserver=http://point.pixka.me:3333 " kykub/pidevice
    - docker image prune -a -f
runproduct:
  stage: product_install
  only:
    refs:
      - master
  tags:
    - product_install
  script:
    - CONTAINER_NAME="pidevice"
    - OLD="$(docker ps --all --quiet --filter=name="$CONTAINER_NAME")"
    - |- 
           if [ -n "$OLD" ]; then
            docker stop $OLD && docker rm $OLD
           fi
    - docker pull kykub/pidevice
    - docker run -p 3334:888 -d -v /root/db:/root/db --name pidevice  --restart always  -e TZ="Asia/Bangkok" -e JAVA_OPTS=" -Xms1024m -Xmx4000m -Dspring.datasource.url=jdbc:h2:/root/db/pp2;AUTO_SERVER=TRUE;IGNORECASE=TRUE  -Dfixip=192.168.88.21  -Dmac=00:e0:4c:68:07:ae  -Dfile.encoding=UTF-8  -Dspring.profiles.active=pc  -Dpiserver=http://192.168.88.21:3333 " kykub/pidevice
    - docker image prune -a -f

.productjk:
  stage: product_install
  only:
    refs:
      - master
  tags:
    - tojk
  script:
    - CONTAINER_NAME="pidevice"
    - OLD="$(docker ps --all --quiet --filter=name="$CONTAINER_NAME")"
    - |-
      if [ -n "$OLD" ]; then
       docker stop $OLD && docker rm $OLD
      fi
    - docker pull kykub/pidevice
    - docker run -p 3334:888 -d -v /root/database:/root/db --name pidevice  --restart always  -e TZ="Asia/Bangkok" -e JAVA_OPTS=" -Xms1024m -Xmx4000m -Dspring.datasource.url=jdbc:h2:/root/db/pp2;AUTO_SERVER=TRUE;IGNORECASE=TRUE  -Dfixip=192.168.1.9  -Dmac=00:e0:4c:68:07:ae  -Dfile.encoding=UTF-8  -Dspring.profiles.active=pc  -Dpiserver=http://192.168.1.9:3333 " kykub/pidevice
    - docker image prune -a -f