stages:
  - build
build_base:
  stage: build
  trigger:
    project: rokkor/pibasekt
    branch: master
    strategy: depend
build:
  stage: build
  tags:
    - build
  script:
    - echo "build"
    - mvn compile -DskipTests=true
