#update server 2 retry 1
stages:
  - build
  - install
  # - product_build
  # - product_install
build_base:
  stage: build
  only:
    refs:
      - master
  trigger:
    project: rokkor/pibasekt
    branch: master
    strategy: depend
install:
  stage: install
  only:
    refs:
      - master
  tags:
    - install
  image: docker:lastest
  services:
    - docker:dind
  before_script:
    - docker login --username kykub --password-stdin < /home/ky/d.txt
    # - docker login -u "$CI_REGISTRY_USER"  -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY 
    # - product_install
  script:
    - mvn install 
    # - ./mvnw package 
    - docker build -t kykub/pidevice --rm .
    - docker push kykub/pidevice
  