stages:
  - build
  - install
build_base:
  stage: build
  only:
    refs:
      - master
  trigger:
    project: rokkor/pibasekt
    branch: master
    strategy: depend
install:
  stage: install
  only:
    refs:
      - master
  tags:
    - install
  script:
    - echo "build"
    - mvn install -DskipTests=true
    - cp target/*.jar /home/ky/
