#update server 2 retry 5
stages:
  - build
  - install
  - runtest
  - product_install
  # - product_build
  # - product_install
build_base:
  stage: build
  only:
    refs:
      - master
  trigger:
    project: rokkor/pibasekt
    branch: master
    strategy: depend


install:
  stage: install
  only:
    refs:
      - master
  tags:
    - install
  image: docker:lastest
  services:
    - docker:dind
  before_script:
    - docker login --username kykub --password-stdin < /home/ky/d.txt
    # - docker login -u "$CI_REGISTRY_USER"  -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY 
    # - product_install
  script:
    - mvn install -Dspring.profiles.active=test
    # - ./mvnw package 
    - docker build -t kykub/pidevice --rm .
    - docker push kykub/pidevice
runtest:
  stage: runtest
  only:
    refs:
      - master
  tags:
    - runtest
  script:
    - CONTAINER_NAME="pidevice"
    - OLD="$(docker ps --all --quiet --filter=name="$CONTAINER_NAME")"
    - |- 
           if [ -n "$OLD" ]; then
            docker stop $OLD && docker rm $OLD
           fi
    - docker pull kykub/pidevice
    - docker run -p 3334:888 -d --name pidevice  -e TZ="Asia/Bangkok" -e JAVA_OPTS=" -Dspring.datasource.url=jdbc:h2:~/pp2;AUTO_SERVER=TRUE;IGNORECASE=TRUE  -Dfixip=192.168.88.20  -Dmac=b8:27:eb:19:8f:5f  -Dfile.encoding=UTF-8  -Dspring.profiles.active=pc  -Dpiserver=http://point.pixka.me:3333 " kykub/pidevice

runproduct:
  stage: product_install
  only:
    refs:
      - master
  tags:
    - product_install
  script:
    - CONTAINER_NAME="pidevice"
    - OLD="$(docker ps --all --quiet --filter=name="$CONTAINER_NAME")"
    - |- 
           if [ -n "$OLD" ]; then
            docker stop $OLD && docker rm $OLD
           fi
    - docker pull kykub/pidevice
    - docker run -p 3334:888 -d --name pidevice  -e TZ="Asia/Bangkok" -e JAVA_OPTS=" -Xms1024m -Xmx6000m -Dspring.datasource.url=jdbc:h2:~/pp2;AUTO_SERVER=TRUE;IGNORECASE=TRUE  -Dfixip=192.168.88.21  -Dmac=00:e0:4c:68:07:ae  -Dfile.encoding=UTF-8  -Dspring.profiles.active=pc  -Dpiserver=http://point.pixka.me:3333 " kykub/pidevice