#update server 2 retry 1
stages:
  - build
  - install
  - product_build
  - product_install
build_base:
  stage: build
  only:
    refs:
      - master
  trigger:
    project: rokkor/pibasekt
    branch: master
    strategy: depend
install:
  stage: install
  only:
    refs:
      - master
  tags:
    - install
    - product_install
  script:
    - echo "build"
    - mvn install -DskipTests=true
    - cp target/pidevice.jar /home/ky/app/pidevice
    - /home/ky/app/pidevice/restart.sh
